sudo: false

language: node_js

node_js:
  - "8"

notifications:
  disabled: true

before_install:
  - npm install -g npm@5

install:
  - npm install -g codecov

env:
  - TEST_DIR=client
  - TEST_DIR=server

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script: cd $TEST_DIR && npm install && npm test && codecov
